.PHONY: clean All

All:
	@echo "----------Building project:[ AutoFunkin - Debug ]----------"
	@cd "AutoFunkin" && "$(MAKE)" -f  "AutoFunkin.mk"
clean:
	@echo "----------Cleaning project:[ AutoFunkin - Debug ]----------"
	@cd "AutoFunkin" && "$(MAKE)" -f  "AutoFunkin.mk" clean
